### ISSUE TITLE
Client Software on Linux? 

### ISSUE THREAD

**Issue by CEngelbrecht** [twyatt/galactic-aztec-heavy-data-acquisition#4] opened 2016-10-31 23:10 UTC
Hi Travis, I'm new to the Galactic Aztec Heavy avionics team as of Fall 2016. On my personal PC I'm running Ubuntu, and was wondering if there was a way to get the data acq software to run on my machine. 

Regards
Christian

**Comment by twyatt** [comment] 2016-10-31 23:33
I'll try to setup some Linux builds for you that could be easily downloaded.

If you're eager to get it going you could follow the [Build From Source](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition#building-from-sourcel) instructions for OS X. The `build.command` script was intended for OS X but the only OS X specific command is that last `open` command that simply opens the output folder for convenience. Everything else in the `build.command` script should be compatible with a standard Linux distro so might be able to build the **client** on your Ubuntu box.

The server side was written specifically for the Raspberry Pi's GPIO, so it might run on your Ubuntu box but only in [testing mode](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition#testing).

**Comment by CEngelbrecht** [comment] 2016-11-01 00:09
Thank you, the build worked.

Under the client/build/libs folder there is client.jar file, but running it with `java -jar client.jar` gives me 

> no main manifest attribute, in client.jar

I'm not used to running Java on my machine, so my apologies if this is obvious.
Under your readme you say to navigate to `client/build/jfx/native/` but jfx does not exist. 

What we're trying to do is transducer calibration, and all the plumbing is set up just fine with our pressure tank, but I couldn't get any readings from the ADC. What I was doing was just running the ReadPressures.py program (not sure if you wrote that?) while SSH'd into the Pi, but as I said this gave no readings. All the ethernet ports were occupied and hooked up to the ducers, but the raw voltage readings from all the ADCs were zero. I've been looking into this client to see if there's a solution here.

**Comment by twyatt** [comment] 2016-11-01 00:24
Did the build produce any files in the `client/build/jfx/native/` folder? As that is where the application launcher would be placed (which would properly launch the `client.jar`, and fix the error you are seeing).

The `ReadPressures.py` was written by [Jacob Dodson](https://github.com/dodson551) I believe.

If you follow the [Getting Started](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition#getting-started) instructions then it should start the server application that I wrote on the Pi:

```
wget -qO- https://github.com/twyatt/galactic-aztec-heavy-data-acquisition/releases/download/1.0.0/server.tar | tar xv
server/bin/server --allow-no-logs
```

The first line will download/install the server software on the Pi. The second line will start the server software.

If it starts properly (without any errors) then press `?` and then `Enter` and it should show you a list of available options, one of which allows you to list the current ADC readings.

You also will need to have the [Galactic Aztec Heavy Raspberry Pi Add-on: ADC](https://github.com/twyatt/galactic-aztec-heavy-rpi-addon-adc) board plugged into the Pi in order to get ADC readings. Alternatively you could launch the server in [Testing mode](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition#testing) to at least run with test data, which might help if you are trying to get the client software to connect with the server.

**Comment by twyatt** [comment] 2016-11-01 05:49
I attempted to build the project in an Ubuntu Docker and had some trouble with ASCII encoding and dependency changes, so I'll try to resolve the issues and push the changes soon so that you can build the client under Ubuntu.

**Comment by CEngelbrecht** [comment] 2016-11-01 15:33
After the build, in my client folder I have these folders. 
- classes
- dependency-cache
- libs
- resources
- tmp

Within classes there are some java class files: 
GaugeController.class 
GaugeSettings.class
MainController$2.class
MainController.class
GaugeController$Mode.class
MainController$1.class
MainController$3.class

But besides that, the folders are pretty sparse. 

Thanks for attempting the build. There is a Windows laptop, Ryan's, that we're also trying to use, but I'm having networking troubles using it. Simply put, trying to SSH into it using Putty isn't working. I know its static IP is 10.42.0.230, I've got internet and network sharing enabled (it's windows 10), and I've tried when firewall is disabled, but I simply can't connect to it. On my machine, a simple `ssh pi@10.42.0.230` works just fine, but I can't get in. Hence, I'm trying to use my ubuntu laptop as the client.

**Comment by CEngelbrecht** [comment] 2016-11-01 22:31
So I tried to rebuild, and I may have been overly optimistic earlier. Now when I rebuild, I have a dependency issue: 

> Build failed with an exception.
> - What went wrong:
>   Could not resolve all dependencies for configuration ':server:compileClasspath'.
>   > Could not find com.pi4j:pi4j-core:1.1-SNAPSHOT.
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/pi4j/pi4j-core/1.1-SNAPSHOT/maven-metadata.xml
>       https://jcenter.bintray.com/com/pi4j/pi4j-core/1.1-SNAPSHOT/pi4j-core-1.1-SNAPSHOT.pom
>       https://jcenter.bintray.com/com/pi4j/pi4j-core/1.1-SNAPSHOT/pi4j-core-1.1-SNAPSHOT.jar
>       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/1.1-SNAPSHOT/maven-metadata.xml
>       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/1.1-SNAPSHOT/pi4j-core-1.1-SNAPSHOT.pom
>       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/1.1-SNAPSHOT/pi4j-core-1.1-SNAPSHOT.jar
>   Required by:
>       twyatt-galactic-aztec-heavy-data-acquisition-b74f9f9:server:unspecified
> 
> > Could not find com.pi4j:pi4j-device:1.1-SNAPSHOT.
> >   Searched in the following locations:
> >       https://jcenter.bintray.com/com/pi4j/pi4j-device/1.1-SNAPSHOT/maven-metadata.xml
> >       https://jcenter.bintray.com/com/pi4j/pi4j-device/1.1-SNAPSHOT/pi4j-device-1.1-SNAPSHOT.pom
> >       https://jcenter.bintray.com/com/pi4j/pi4j-device/1.1-SNAPSHOT/pi4j-device-1.1-SNAPSHOT.jar
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-device/1.1-SNAPSHOT/maven-metadata.xml
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-device/1.1-SNAPSHOT/pi4j-device-1.1-SNAPSHOT.pom
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-device/1.1-SNAPSHOT/pi4j-device-1.1-SNAPSHOT.jar
> >   Required by:
> >       twyatt-galactic-aztec-heavy-data-acquisition-b74f9f9:server:unspecified
> > 
> > Could not find com.pi4j:pi4j-gpio-extension:1.1-SNAPSHOT.
> >   Searched in the following locations:
> >       https://jcenter.bintray.com/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/maven-metadata.xml
> >       https://jcenter.bintray.com/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/pi4j-gpio-extension-1.1-SNAPSHOT.pom
> >       https://jcenter.bintray.com/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/pi4j-gpio-extension-1.1-SNAPSHOT.jar
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/maven-metadata.xml
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/pi4j-gpio-extension-1.1-SNAPSHOT.pom
> >       https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-gpio-extension/1.1-SNAPSHOT/pi4j-gpio-extension-1.1-SNAPSHOT.jar
> >   Required by:
> >       twyatt-galactic-aztec-heavy-data-acquisition-b74f9f9:server:unspecified

**Comment by twyatt** [comment] 2016-11-01 22:36
Yup, that is the dependency issue I saw as well. I'll try to fix that soon.

**Comment by CEngelbrecht** [comment] 2016-11-01 23:32
In the meantime: 

I can run the server on the Pi with the ADC board attached, and run `a` when the server is running with `--allow-no-logs` to show instantaneous ADC values, but I'd like to be able to log them. We have a tank with air to calibrate with for the next few hours. Is this possible?

**Comment by twyatt** [comment] 2016-11-01 23:47
The logging simply needs a folder to save logs to, so just make a folder,
say "logs" for example, then run the server with that folder as it's only
argument and it will save the ADC log data to that folder.

**Comment by CEngelbrecht** [comment] 2016-11-02 00:04
Ah, perfect.

**Comment by CEngelbrecht** [comment] 2016-11-02 00:24
One more stupid question: A0 through A5 correspond to LOX, Kero, Motor and Helium (and RCS low and high, but those aren't hooked up right now). Are they in that order? Apologies if this is documented somewhere obvious. I.e is A0 Lox, A1 Kero, etc

**Comment by twyatt** [comment] 2016-11-02 00:43
The client software is setup for the [following configuration](https://raw.githubusercontent.com/twyatt/galactic-aztec-heavy-data-acquisition/master/artwork/client_gauges.png):

| Channel | Pressure Transducer Location |
| --- | --- |
| A0 | LOX |
| A1 | Kerosene |
| A2 | Helium |
| A3 | Motor |
| A4 | RCS Low |
| A5 | RCS High |

But the actual configuration totally depends on how you hook up the [Galactic Aztec Heavy Raspberry Pi Add-on: ADC](https://github.com/twyatt/galactic-aztec-heavy-rpi-addon-adc) board. The ports on that board are [labeled](https://raw.githubusercontent.com/twyatt/galactic-aztec-heavy-rpi-addon-adc/master/artwork/top.png) with the A0, A1, etc channels.

**Comment by CEngelbrecht** [comment] 2016-11-02 00:51
We've hooked it up in that configuration. I just wanted to make sure there wasn't a built in software bias towards a particular line, so if we calibrated the lox ducer while it was hooked up to, say A1, and the software assumed it was a kero ducer, then that would make all sorts of issues I'm sure.

**Comment by twyatt** [comment] 2016-11-02 01:00
The software doesn't treat the data any differently on the different channels, so as long as you are consistent (use the same channel for the same transducer when calibrating and when recording data) then you'll be fine.

The only thing the software does is **display** the data differently per channel. Depending on the calibration values that are set in the software it will read different pressures, **but** it will always record unmodified raw voltage readings.

Also, the [Galactic Aztec Heavy Raspberry Pi Add-on: ADC](https://github.com/twyatt/galactic-aztec-heavy-rpi-addon-adc) has different ADC chips on channels A4 and A5 than A0 through A3 (see [specifications](https://github.com/twyatt/galactic-aztec-heavy-rpi-addon-adc#specifications) for details). Basically, A0 through A3 will be able to read data faster and with more accuracy because those channels are running the higher end ADS1114 chip.

**Comment by twyatt** [comment] 2016-11-02 05:55
@CEngelbrecht please try [dataacquisitionclient-1.0.1.deb](https://drive.google.com/file/d/0B8mEv6E1QAKccjc5MWQ0UXBuNWs/view?usp=sharing) and let me know if it works for you.

```
sudo dpkg -i dataacquisitionclient-1.0.1.deb && sudo apt-get install -f
```

**Comment by CEngelbrecht** [comment] 2016-11-02 15:00
The dkpg and install went off without a hitch. I can run `java -jar data-acquisition-client.jar` in the app folder, which brings up the GUI. 

In the main DataAcquisitionClient folder, running `./DataAcquisitionClient` does not work, giving 

> DataAcquisitionClient Class client/Launcher not found.
> DataAcquisitionClient Failed to launch JVM

but I'm assuming this is not a problem.

**Comment by twyatt** [comment] 2016-11-02 18:09
I suspect the error you're receiving is related to [javafx-maven-plugin issue #124](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/124). The [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) is a tool used to package the project.

Running the application directly using `java -jar data-acquisition-client.jar` is totally fine. Glad it worked for you!

I'll push the changes (and add documentation) so that a Linux distribution is part of the releases published to GitHub when updates are made to the project; so that if any changes are made it will be easy for you to update your installation.

If I have time I'll look into fixing the launcher error you're seeing, but since it works running it directly with Java, it is pretty low on my list, so it's not likely I'll get to it anytime soon.

**Comment by twyatt** [comment] 2016-11-03 08:28
Updated build scripts to include Linux packages in the release cycle (on the [latest release](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition/releases/latest) page) and added Linux specific documentation to the [readme](https://github.com/twyatt/galactic-aztec-heavy-data-acquisition/blob/master/README.md).

Also note that all `1.0.x` versions are compatible with each other. So a `1.0.1` client can connect and work with a `1.0.0` server (and visa versa).

Opened issue #5 to later address the Linux launcher `Class client/Launcher not found` error.

Closing out this issue, feel free to create more issues if you need further assistance.

**Closed as completed by twyatt** 2016-11-03 08:28 UTC
